#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 26 15:01:46 2019
@author: Tom
"""
import requests

# Ask how many ORFs the user wants to use
n = input('Input the number of ORFs you would like to use')

IDs = {}    # A dictionary of BASIC part names (Keys) and Ensembl IDs (Values)
BASICs = {} # A dictionary of BASIC part names (Keys) and BASIC sequence (Values)

# Ask for each Ensembl ID and add it to the IDs list
for i in range(int(n)):
    ID  = input('Enter the Ensembl ID of ORF {}: '.format(i+1))
    Key = input('And now an identifying 3 letter short code: ')
    IDs[ID] = 'BASIC_'+ Key + '_ORF'
    
# Retrieve the ORF sequence from Ensembl and add BASIC iP/iS 
server = "https://rest.ensembl.org"
for ID in IDs:
    r = requests.get(server+'/sequence/id/'+ID,headers={"Content-type" : "text/plain"})
    #search sequence for BsaI sites
    #replace any BsaI sites without changing amino acids- might have trouble with frame reading but should be able to just replace codons
    #search new sequence again to check its now fixed
    BASICs[IDs[ID]] = 'TCTGGTGGGTCTCTGTCC' + r.text + 'GGCTCGGGAGACCTATCG' 

# Say a lactase gene was imported, with the short code 'LAC', the sequence would be indexed by BASICs['BASIC_LAC_ORF']

ratio = input('Enter the ratio of these ORFs in the format 1,2,3: ')

RBSstrength = {"RBS-A12": 0,
               "RBS-A06": 1,
               "RBS-A11": 1,
               "RBS-A02": 3,
               "RBS-A04": 3,
               "RBS-A05": 4,
               "RBS1": 5,
               "RBS-A09": 14,
               "RBS-A01": 23,
               "RBS-A08": 35,
               "RBS-A03": 46,
               "RBS-A10": 54,
               "RBS2": 56,
               "RBS-A07": 69,
               "RBS3": 100}
#I have no idea how to get this to calculate which RBS matches which ratio???
