#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 26 15:01:46 2019
@author: Tom
"""
import requests

# Ask how many ORFs the user wants to use
n = input('Input the number of ORFs you would like to use')

IDs = {}    # A dictionary of BASIC part names (Keys) and Ensembl IDs (Values)
BASICs = {} # A dictionary of BASIC part names (Keys) and BASIC sequence (Values)

# Ask for each Ensembl ID and add it to the IDs list
for i in range(int(n)):
    ID  = input('Enter the Ensembl ID of ORF {}: '.format(i+1))
    Key = input('And now an identifying 3 letter short code: ')
    IDs[ID] = 'BASIC_'+ Key + '_ORF'
    
# Retrieve the ORF sequence from Ensembl and add BASIC iP/iS 
server = "https://rest.ensembl.org"
for ID in IDs:
    r = requests.get(server+'/sequence/id/'+ID,headers={"Content-type" : "text/plain"})
    BASICs[IDs[ID]] = 'TCTGGTGGGTCTCTGTCC' + r.text + 'GGCTCGGGAGACCTATCG' 

# Say a lactase gene was imported, with the short code 'LAC', the sequence would be indexed by BASICs['BASIC_LAC_ORF']
